### ISSUE TITLE
Fix Travis

### ISSUE THREAD

**Issue by pzuraq** [ember-decorators/ember-decorators#237]
Travis is currently failing to build the application or run tests at all. It appears to be running out of space. The first build where this occured was [here](https://travis-ci.org/ember-decorators/ember-decorators/builds/378873616), it happened mid build. Since then, every build has been red.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: watch /home/travis/build/ember-decorators/ember-decorators/packages/controller/node_modules/os-shim/lib ENOSPC
    at exports._errnoException (util.js:1020:11)
    at FSWatcher.start (fs.js:1451:19)
    at Object.fs.watch (fs.js:1478:11)
    at createFsWatchInstance (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:408:19)
    at FSWatcher.<anonymous> (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:456:19)
    at FSWatcher.<anonymous> (/home/travis/build/ember-decorators/ember-decorators/packages/-ember-decorators/node_modules/chokidar/lib/nodefs-handler.js:461:16)
    at FSReqWrap.oncomplete (fs.js:123:15)
Result: false
```

**Comment by rwjblue** [comment]
Maybe need to flush the caches?

**Comment by pzuraq** [comment]
I've flushed them, they don't appear to be coming back and are empty right now

<img width="456" alt="screen shot 2018-05-19 at 2 37 33 pm" src="https://user-images.githubusercontent.com/685518/40273277-333780bc-5b72-11e8-8325-abcb34fb6116.png">

**Comment by rwjblue** [comment]
The stack seems to point to FS watching (e.g. inotify) issue.  Maybe something [like this](https://stackoverflow.com/questions/22475849/node-js-error-enospc#32600959):

```
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

?

**Comment by rwjblue** [comment]
We could also try to run this on the GCE environment (adding `sudo: required` to `.travis.yml`)...

**Comment by pzuraq** [comment]
👍 will give it a shot, I tried to run it with `sudo: required` but didn’t try manipulating watch params or anything like that

**Comment by pzuraq** [comment]
Appears to have fixed it! Thanks for the help 😄🎉
