### ISSUE TITLE
Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag

### ISSUE THREAD

**Issue by allthesignals** [ember-decorators/ember-decorators#238]
Bumping from 2.0.0 to 2.1.0 throws this build error:

Build Error (Babel) in @ember-decorators/argument/-debug/utils/validation-decorator.js

> @ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
>
> Stack Trace and Error Report: > /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/error.dump.04e1ceb0540a0faec04d6aeb96e8f597.log

<details>

<summary>Full Stacktrace</summary>
=================================================================================

ENV Summary:

  TIME: Sat May 19 2018 17:00:53 GMT-0400 (EDT)
  TITLE: ember
  ARGV:
  - /Users/mgardner/.nvm/versions/node/v8.6.0/bin/node
  - /Users/mgardner/.nvm/versions/node/v8.6.0/bin/ember
  - test
  - --server
  EXEC_PATH: /Users/mgardner/.nvm/versions/node/v8.6.0/bin/node
  TMPDIR: /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T
  SHELL: /bin/bash
  PATH:
  - /Library/Frameworks/Python.framework/Versions/3.6/bin
  - /usr/local/opt/gdal2/bin
  - /Users/mgardner/.nvm/versions/node/v8.6.0/bin
  - /Users/mgardner/.rvm/gems/ruby-2.4.1/bin
  - /Users/mgardner/.rvm/gems/ruby-2.4.1@global/bin
  - /Users/mgardner/.rvm/rubies/ruby-2.4.1/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/go/bin
  - /Users/mgardner/.rvm/bin
  - /Users/mgardner/.rvm/bin
  - node_modules/.bin
  PLATFORM: darwin x64
  FREEMEM: 2859188224
  TOTALMEM: 17179869184
  UPTIME: 2669954
  LOADAVG: 2.40087890625,2.94384765625,2.96337890625
  CPUS:
  - Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz - 3100
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.6.0
  - openssl: 1.0.2l
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.14.1
  - v8: 6.0.287.53
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: @ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
    at /Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:211:17
    at Array.forEach (<anonymous>)
    at Macros._detectForeignFeatureFlag (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:209:18)
    at Macros._cleanImports (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:234:22)
    at Macros.expand (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:66:12)
    at PluginPass.exit (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/index.js:62:29)
    at newFn (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/mgardner/ember-labs-maps/node_modules/babel-core/lib/transformation/file/index.js:516:35)
  - codeFrame: @ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
  - errorMessage: Build Canceled: Broccoli Builder ran into an error with `Babel` plugin. 💥
@ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @ember-decorators/argument/-debug/utils/validation-decorator.js
    - line: [undefined]
    - treeDir: /Users/mgardner/ember-labs-maps/tmp/broccoli_persistent_filterbabel__babel_ember_decoratorsargument-input_base_path-PxcD8yKf.tmp
  - message: Build Canceled: Broccoli Builder ran into an error with `Babel` plugin. 💥
@ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
  - name: Error
  - nodeAnnotation: Babel
  - nodeName: Babel
  - originalErrorMessage: @ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
  - stack: Error: @ember-decorators/argument/-debug/utils/validation-decorator.js: Imported IS_EMBER_2 from ember-compatibility-helpers which is not a supported flag.
    at /Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:211:17
    at Array.forEach (<anonymous>)
    at Macros._detectForeignFeatureFlag (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:209:18)
    at Macros._cleanImports (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:234:22)
    at Macros.expand (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/lib/utils/macros.js:66:12)
    at PluginPass.exit (/Users/mgardner/ember-labs-maps/node_modules/babel-plugin-debug-macros/dist/index.js:62:29)
    at newFn (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/path/context.js:117:8)
    at TraversalContext.visitQueue (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitSingle (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:108:19)
    at TraversalContext.visit (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/context.js:192:19)
    at Function.traverse.node (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/index.js:114:17)
    at traverse (/Users/mgardner/ember-labs-maps/node_modules/babel-traverse/lib/index.js:79:12)
    at File.transform (/Users/mgardner/ember-labs-maps/node_modules/babel-core/lib/transformation/file/index.js:516:35)

=================================================================================

</details>

**Comment by allthesignals** [comment]
Needed to version bump "@ember-decorators/argument": "0.8.13" to 0.8.15. Keep forgetting this is a separate package!
